"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import warnings
from datetime import timedelta
from pathlib import Path

import dj_database_url
import sentry_sdk
from decouple import config
from sentry_sdk.integrations.django import DjangoIntegration

# -------------------------------------------------------------------
# Base directory
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------------------------------------------
# Core env / security
# -------------------------------------------------------------------

SECRET_KEY = config("SECRET_KEY")

DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,testserver",
).split(",")


# -------------------------------------------------------------------
# Applications
# -------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "django.contrib.sites",
    "rest_framework",
    "drf_spectacular",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.openid",
    "allauth.socialaccount.providers.steam",
    "corsheaders",
    "django_filters",
    "notifications",
    "import_export",
    "apps.users",
    "apps.games",
    "apps.core",
    "apps.social",
    "apps.library",
    "apps.recommendations",
    "apps.reviews",
    "apps.realtime",
    "apps.matchmaking",
    "apps.game_tickets",
    "apps.chat",
    "django_fsm",
    "api",
]


# -------------------------------------------------------------------
# Middleware
# -------------------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "apps.users.middleware.IgnoreInvalidJWTMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# -------------------------------------------------------------------
# Auth / Users / Allauth / REST / JWT
# -------------------------------------------------------------------

AUTH_USER_MODEL = "users.CustomUser"

REST_USE_JWT = True
TOKEN_MODEL = None
REST_AUTH_TOKEN_MODEL = None

ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # Pas de username
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"

ACCOUNT_EMAIL_VERIFICATION = config("ACCOUNT_EMAIL_VERIFICATION", default="mandatory")
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = True

SITE_ID = 1

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # JWT via cookies (dj-rest-auth)
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
        # JWT via header Authorization: Bearer <token>
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Pratique pour l'admin / browsable API
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        # Bloque les utilisateurs suspendus sur tous les endpoints protégés
        "apps.users.permissions.IsNotSuspended",
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "apps.users.exceptions.custom_exception_handler",
}

# Cookies JWT / Samesite
JWT_AUTH_COOKIE = "access_token"
JWT_AUTH_REFRESH_COOKIE = "refresh_token"
JWT_AUTH_HTTPONLY = True
JWT_AUTH_SECURE = not DEBUG
JWT_AUTH_SAMESITE = "None" if not DEBUG else "Lax"

REST_AUTH = {
    "USE_JWT": True,
    "TOKEN_MODEL": None,
    "JWT_AUTH_COOKIE": JWT_AUTH_COOKIE,
    "JWT_AUTH_REFRESH_COOKIE": JWT_AUTH_REFRESH_COOKIE,
    "JWT_AUTH_HTTPONLY": JWT_AUTH_HTTPONLY,
    "JWT_AUTH_SECURE": JWT_AUTH_SECURE,
    "JWT_AUTH_SAMESITE": JWT_AUTH_SAMESITE,
    "REGISTER_SERIALIZER": "apps.users.serializers.CustomRegisterSerializer",
    "USER_DETAILS_SERIALIZER": "apps.users.serializers.UserSerializer",
    "OLD_PASSWORD_FIELD_ENABLED": True,
}

REST_AUTH_SERIALIZERS = {
    "JWT_TOKEN_CLAIMS_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=config("JWT_ACCESS_TOKEN_LIFETIME", default=15, cast=int)),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=config("JWT_REFRESH_TOKEN_LIFETIME", default=10080, cast=int)),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# -------------------------------------------------------------------
# Security / CORS / CSRF / Cookies
# -------------------------------------------------------------------

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Le cookie CSRF doit être lisible par le frontend pour pouvoir être
# renvoyé dans le header X-CSRFToken sur les requêtes POST/PATCH/DELETE.
CSRF_COOKIE_HTTPONLY = False


CORS_ALLOWED_ORIGINS = [o for o in config("CORS_ALLOWED_ORIGINS", default="").split(",") if o]

CORS_ALLOW_CREDENTIALS = config("CORS_ALLOW_CREDENTIALS", default=True, cast=bool)

#
CSRF_TRUSTED_ORIGINS = [o for o in config("CSRF_TRUSTED_ORIGINS", default="").split(",") if o]


# -------------------------------------------------------------------
# URLs / WSGI / API docs
# -------------------------------------------------------------------

ROOT_URLCONF = "config.urls"

ASGI_APPLICATION = "config.asgi.application"

SPECTACULAR_SETTINGS = {
    "TITLE": "LudoKan API",
    "DESCRIPTION": "API documentation",
    "VERSION": "1.0.0",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# -------------------------------------------------------------------
# Database
# -------------------------------------------------------------------

DATABASES = {
    "default": dj_database_url.config(
        default=config(
            "DATABASE_URL",
            default=(
                f"postgresql://{config('POSTGRES_USER', default='tesp_user')}:"
                f"{config('POSTGRES_PASSWORD', default='tesp_password')}@"
                f"{config('POSTGRES_HOST', default='db')}:"
                f"{config('POSTGRES_PORT', default='5432')}/"
                f"{config('POSTGRES_DB', default='tesp_db')}"
            ),
        ),
        conn_max_age=600,
    )
}

# Mettre ssl_require=True  dans la configuration si Render nécessite SSL obligatoire

# -------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# -------------------------------------------------------------------
# Internationalization
# -------------------------------------------------------------------

LANGUAGE_CODE = "en-us"


TIME_ZONE = config("TIME_ZONE", default="Europe/Paris")

USE_I18N = True

USE_TZ = True


# -------------------------------------------------------------------
# Static files
# -------------------------------------------------------------------

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# -------------------------------------------------------------------
# Media files (upload)
# -------------------------------------------------------------------

if DEBUG:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
else:
    # Utilise Cloudflare R2 (compatible S3) pour le stockage des fichiers
    INSTALLED_APPS += ["storages"]

    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

    # Endpoint R2 type: https://<account_id>.r2.cloudflarestorage.com
    AWS_S3_ENDPOINT_URL = config("CLOUDFLARE_R2_ENDPOINT")
    AWS_ACCESS_KEY_ID = config("CLOUDFLARE_R2_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("CLOUDFLARE_R2_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = config("CLOUDFLARE_R2_BUCKET_NAME")
    AWS_S3_REGION_NAME = "auto"
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_SIGNATURE_VERSION = "s3v4"

    # Optionnel : permet d'ajouter un préfixe (ex: "prod" ou "staging")
    # pour organiser les fichiers dans un même bucket R2.
    # Exemple: CLOUDFLARE_R2_PREFIX=staging => clés "staging/avatars/..."
    AWS_LOCATION = config("CLOUDFLARE_R2_PREFIX", default="").strip() or None

    # Optionnel : domaine Cloudflare/Custom pour servir les fichiers
    # (ex: cdn.ludokan.com). Si non défini, l'URL R2 par défaut est utilisée.
    AWS_S3_CUSTOM_DOMAIN = config("CLOUDFLARE_R2_CUSTOM_DOMAIN", default=None)


# -------------------------------------------------------------------
# Default primary key
# -------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# -------------------------------------------------------------------
# Celery
# -------------------------------------------------------------------

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://redis:6379/1")
CELERY_CACHE_BACKEND = config("CELERY_CACHE_BACKEND", default="redis://redis:6379/2")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
# Évite l'avertissement Celery 6 sur broker_connection_retry au démarrage
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


# -------------------------------------------------------------------
# Cache (Redis)
# -------------------------------------------------------------------

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("REDIS_URL", default="redis://redis:6379/2"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


# -------------------------------------------------------------------
# Channels (WebSockets via Redis)
# -------------------------------------------------------------------

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # URL Redis dédiée aux websockets (DB 3 par défaut).
            # Surchageable via la variable d'env CHANNEL_REDIS_URL,
            # ex: redis://127.0.0.1:6379/3 en dev hors Docker.
            "hosts": [
                config("CHANNEL_REDIS_URL", default="redis://redis:6379/3"),
            ],
        },
    }
}

# -------------------------------------------------------------------
# Environment
# -------------------------------------------------------------------

ENVIRONMENT = config("ENVIRONMENT", default="local")


# -------------------------------------------------------------------
# Email
# -------------------------------------------------------------------

DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@ludokan.com")
SERVER_EMAIL = config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = config("EMAIL_SUBJECT_PREFIX", default="[LudoKan] ")
ACCOUNT_EMAIL_SUBJECT_PREFIX = config("ACCOUNT_EMAIL_SUBJECT_PREFIX", default=EMAIL_SUBJECT_PREFIX)

EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)

EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=10, cast=int)

EMAIL_QUOTA_ENABLED = config("EMAIL_QUOTA_ENABLED", default=True, cast=bool)
EMAIL_DAILY_LIMIT = config("EMAIL_DAILY_LIMIT", default=80, cast=int)
EMAIL_MONTHLY_LIMIT = config("EMAIL_MONTHLY_LIMIT", default=2500, cast=int)
EMAIL_ALLOWLIST_ENABLED = config("EMAIL_ALLOWLIST_ENABLED", default=False, cast=bool)
EMAIL_ALLOWLIST = [e.strip() for e in config("EMAIL_ALLOWLIST", default="").split(",") if e.strip()]

# -------------------------------------------------------------------
# SITE ID & DOMAIN
# -------------------------------------------------------------------
SITE_ID = config("SITE_ID", default=1, cast=int)
SITE_DOMAIN = config("SITE_DOMAIN", default="ludokan-local.fr")
SITE_NAME = config("SITE_NAME", default="Ludokane Local")

# -------------------------------------------------------------------
# Logging centralisé -> system_logs
# -------------------------------------------------------------------

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "system_logs": {
            "class": "apps.core.logging_handlers.SystemLogHandler",
            "level": "INFO",
        },
    },
    "loggers": {
        "system_logs": {
            "level": "INFO",
            "handlers": ["system_logs"],
            "propagate": False,
        },
        "django.request": {
            "level": "ERROR",
            "handlers": ["system_logs"],
            "propagate": True,
        },
    },
}


# -------------------------------------------------------------------
# Sentry
# -------------------------------------------------------------------

SENTRY_DSN = config("SENTRY_DSN", default="").strip()

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=config(
            "SENTRY_TRACES_SAMPLE_RATE",
            default=1.0,
            cast=float,
        ),
        environment=config("SENTRY_ENVIRONMENT", default=None),
        send_default_pii=True,
    )

# Réduire le bruit : avertissement django-fsm / viewflow (en fin de fichier pour Ruff E402)
warnings.filterwarnings("ignore", category=UserWarning, module="django_fsm")

# -------------------------------------------------------------------
# Steam API & Provider Config
# -------------------------------------------------------------------

STEAM_API_KEY = config("STEAM_API_KEY", default="")
STEAM_REDIRECT_URL = config("STEAM_REDIRECT_URL", default="")

SOCIALACCOUNT_PROVIDERS = {
    "steam": {
        "APP": {
            "client_id": STEAM_API_KEY,
            "secret": "",
            "key": "",
        }
    }
}
