# Generated by Django 4.2.30 on 2026-05-11 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_a",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="friendships_as_low", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "user_b",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="friendships_as_high", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Amitié",
                "verbose_name_plural": "Amitiés",
            },
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("accepted", "Acceptée"), ("declined", "Refusée"), ("cancelled", "Annulée")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="friend_requests_sent", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="friend_requests_received", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d’ami",
                "verbose_name_plural": "Demandes d’amis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(fields=("user_a", "user_b"), name="social_friendship_user_pair_uniq"),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.CheckConstraint(check=models.Q(("user_a_id__lt", models.F("user_b_id"))), name="social_friendship_ordered_users"),
        ),
        migrations.AddIndex(
            model_name="friendrequest",
            index=models.Index(fields=["to_user", "status"], name="social_frie_to_user_38f395_idx"),
        ),
        migrations.AddIndex(
            model_name="friendrequest",
            index=models.Index(fields=["from_user", "status"], name="social_frie_from_us_458f66_idx"),
        ),
        migrations.AddConstraint(
            model_name="friendrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")), fields=("from_user", "to_user"), name="social_friendrequest_pending_pair_uniq"
            ),
        ),
    ]
