# Generated by Django 4.2.7 on 2026-01-03 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0009_alter_game_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("active", "Active"), ("closed", "Closed")], default="active", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches", to="games.game")),
                (
                    "player1",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches_as_player1", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "player2",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches_as_player2", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchmakingRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("geohash", models.CharField(blank=True, max_length=12)),
                ("radius_km", models.PositiveIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("matched", "Matched"), ("expired", "Expired")], default="pending", max_length=10
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matchmaking_requests", to="games.game")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matchmaking_requests", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "expires_at"], name="matchmaking_status_986fcb_idx"),
                    models.Index(fields=["latitude", "longitude"], name="matchmaking_latitud_0e53c4_idx"),
                    models.Index(fields=["geohash"], name="matchmaking_geohash_042289_idx"),
                ],
            },
        ),
    ]
