# Generated by Django 4.2.7 on 2026-01-02 23:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0008_alter_game_description_alter_genre_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchmakingSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchmakingRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("radius_km", models.PositiveIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("matched", "Matched"), ("expired", "Expired")], default="pending", max_length=10
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matchmaking_requests", to="games.game")),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="matchmaking.matchmakingsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matchmaking_requests", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["status", "expires_at"], name="matchmaking_status_986fcb_idx")],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("active", "Active"), ("closed", "Closed")], default="active", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches", to="games.game")),
                (
                    "player1",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches_as_player1", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "player2",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches_as_player2", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["status", "created_at"], name="matchmaking_status_06277d_idx")],
                "unique_together": {("player1", "player2", "game")},
            },
        ),
    ]
