# Generated by Django 4.2.7 on 2026-01-02 23:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matchmaking", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="matchmakingrequest",
            index=django.contrib.postgres.indexes.GistIndex(fields=["location"], name="matchmaking_locatio_e32cef_gist"),
        ),
    ]
