# Generated by Django 4.2.29 on 2026-04-22 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0015_game_steam_appid"),
        ("matchmaking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameParty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert / En formation"),
                            ("countdown", "Compte à rebours en cours"),
                            ("chat_active", "Discussion active"),
                            ("cancelled", "Annulé"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("max_players", models.PositiveIntegerField(default=2)),
                ("countdown_ends_at", models.DateTimeField(blank=True, null=True)),
                ("chat_room_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="parties", to="games.game")),
            ],
        ),
        migrations.CreateModel(
            name="GamePartyMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ready", models.BooleanField(default=False)),
                ("ready_for_chat", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("party", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="members", to="matchmaking.gameparty")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("party", "user")},
            },
        ),
    ]
