# Generated by Django 4.2.7 on 2025-12-09 20:59

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[apps.users.validators.validate_avatar],
            ),
        ),
    ]
