# Generated by Django 4.2.7 on 2026-01-23 13:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_customuser_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSuspension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField()),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suspended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspensions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="suspensions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "User suspension",
                "verbose_name_plural": "User suspensions",
                "ordering": ["-start_date"],
                "indexes": [models.Index(fields=["user", "is_active", "end_date"], name="users_users_user_id_762d91_idx")],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("moderator", "Moderator"), ("admin", "Admin"), ("superadmin", "Super admin")], max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="roles", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "User role",
                "verbose_name_plural": "User roles",
                "unique_together": {("user", "role")},
            },
        ),
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_type", models.CharField(max_length=64)),
                ("target_type", models.CharField(help_text="Type de cible (user, review, rating, game, ...).", max_length=64)),
                ("target_id", models.PositiveBigIntegerField(blank=True, help_text="Identifiant de la cible dans sa table.", null=True)),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="admin_actions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin action",
                "verbose_name_plural": "Admin actions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["action_type"], name="users_admin_action__f6a1e4_idx"),
                    models.Index(fields=["target_type", "target_id"], name="users_admin_target__4300b3_idx"),
                ],
            },
        ),
    ]
