# Generated by Django 4.2.29 on 2026-03-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_usersuspension_userrole_adminaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar_url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="description_courte",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
