# Generated by Django 4.2.29 on 2026-04-03 10:05

from django.db import migrations, models

import apps.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_avatar_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/", validators=[apps.users.validators.validate_avatar]),
        ),
        migrations.AddField(
            model_name="customuser",
            name="banner_url",
            field=models.URLField(blank=True),
        ),
    ]
