# Generated by Django 4.2.29 on 2026-04-09 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customuser_banner_customuser_banner_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SteamProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("steam_id", models.CharField(help_text="SteamID64 de l'utilisateur", max_length=64, unique=True)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("profile_url", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="steam_profile", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Steam Profile",
                "verbose_name_plural": "Steam Profiles",
            },
        ),
    ]
