# Generated by Django 4.2.30 on 2026-04-30 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_fix_empty_user_pseudos"),
    ]

    operations = [
        migrations.CreateModel(
            name="XboxProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("xbox_xuid", models.CharField(help_text="Xbox User ID (XUID)", max_length=64, unique=True)),
                ("gamertag", models.CharField(blank=True, max_length=255)),
                ("gamerscore", models.IntegerField(default=0)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="xbox_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Xbox Profile",
                "verbose_name_plural": "Xbox Profiles",
            },
        ),
    ]
