# Generated by Django 4.2.30 on 2026-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_xboxprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language_preference",
            field=models.CharField(default="fr", max_length=5),
        ),
        migrations.AddField(
            model_name="customuser",
            name="theme_preference",
            field=models.CharField(default="system", max_length=10),
        ),
    ]
