# Generated by Django 4.2.29 on 2026-03-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_system_logs_activity_logs_report_schedules"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="core_activi_user_id_599332_idx",
            old_name="core_activi_user_id_8f3d2b_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="core_activi_action_4055cf_idx",
            old_name="core_activi_action_9e4c1a_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="core_activi_target__d3fcab_idx",
            old_name="core_activi_target__7b5a0d_idx",
        ),
        migrations.RenameIndex(
            model_name="reportschedule",
            new_name="core_report_enabled_4bb707_idx",
            old_name="core_report_enabled_1d6e7f_idx",
        ),
        migrations.RenameIndex(
            model_name="systemlog",
            new_name="core_system_event_t_23458c_idx",
            old_name="core_system_event_t_2a1c4a_idx",
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="next_run",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
