# Generated by Django 4.2.29 on 2026-05-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamepartymember",
            name="wants_to_start_early",
            field=models.BooleanField(default=False, help_text="True si le joueur a cliqué sur 'Lancer tout de suite' pendant la phase OPEN."),
        ),
    ]
