# Generated by Django 4.2.7 on 2026-01-22 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0009_alter_game_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("game_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("players", models.CharField(blank=True, help_text="Ex: 1-4, 2+, solo", max_length=50)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("genres", models.ManyToManyField(blank=True, related_name="game_tickets", to="games.genre")),
                ("platforms", models.ManyToManyField(blank=True, related_name="game_tickets", to="games.platform")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="game_tickets", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="game_ticket_user_id_f38594_idx"),
                    models.Index(fields=["status"], name="game_ticket_status_8ed0bf_idx"),
                    models.Index(fields=["created_at"], name="game_ticket_created_5b5931_idx"),
                ],
            },
        ),
    ]
