# Generated by Django 4.2.7 on 2026-01-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameTicketAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="game_tickets/attachments/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="game_tickets.gameticket")),
            ],
        ),
    ]
