# Generated by Django 4.2.7 on 2026-01-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_tickets", "0002_gameticketattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameticket",
            name="players",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="gameticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewing", "Reviewing"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
