# Generated by Django 4.2.7 on 2026-01-31 21:28

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game_tickets", "0003_alter_gameticket_players_alter_gameticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameticket",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewing", "Reviewing"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                protected=True,
            ),
        ),
    ]
