# Generated by Django 4.2.7 on 2026-02-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_tickets", "0004_alter_gameticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameticket",
            name="admin_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="gameticket",
            name="internal_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gameticket",
            name="internal_note",
            field=models.TextField(blank=True),
        ),
    ]
