# Generated by Django 4.2.7 on 2026-02-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_tickets", "0005_gameticket_admin_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameticket",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameticket",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
