# Generated by Django 4.2.7 on 2026-02-06 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game_tickets", "0006_gameticket_rejection_reason_gameticket_reviewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameticket",
            name="reviewer",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_tickets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
