# Generated by Django 4.2.28 on 2026-03-02 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game_tickets", "0007_gameticket_reviewer"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameTicketHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "old_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Reviewing"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Reviewing"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_history_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history", to="game_tickets.gameticket")),
            ],
            options={
                "verbose_name_plural": "Game ticket histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameTicketComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="game_tickets.gameticket")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
