# Generated by Django 4.2.29 on 2026-03-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_tickets", "0008_gametickethistory_gameticketcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameticket",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
