# Generated by Django 4.2.7 on 2025-12-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="igdb_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="genre",
            name="igdb_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="platform",
            name="igdb_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="publisher",
            name="igdb_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
