# Generated by Django 4.2.7 on 2025-12-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_game_igdb_id_genre_igdb_id_platform_igdb_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="cover_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
