# Generated by Django 4.2.7 on 2025-12-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_game_cover_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
