# Generated by Django 4.2.7 on 2025-12-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_game_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("released", "Released"),
                    ("alpha", "Alpha"),
                    ("beta", "Beta"),
                    ("early_access", "Early Access"),
                    ("offline", "Offline"),
                    ("cancelled", "Cancelled"),
                    ("rumored", "Rumored"),
                    ("delisted", "Delisted"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
