# Generated by Django 4.2.7 on 2025-12-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0006_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="game",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rating",
            name="normalized_value",
            field=models.FloatField(default=0.0),
        ),
    ]
