# Generated by Django 4.2.7 on 2025-12-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0007_game_average_rating_game_rating_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="platform",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
