# Generated by Django 4.2.7 on 2026-01-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0008_alter_game_description_alter_genre_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("released", "Released"),
                    ("alpha", "Alpha"),
                    ("beta", "Beta"),
                    ("early_access", "Early Access"),
                    ("offline", "Offline"),
                    ("cancelled", "Cancelled"),
                    ("rumored", "Rumored"),
                    ("delisted", "Delisted"),
                ],
                default="released",
                max_length=20,
            ),
        ),
    ]
