# Generated by Django 4.2.28 on 2026-03-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0009_alter_game_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["min_age"], name="games_min_age_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["min_players"], name="games_min_players_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["max_players"], name="games_max_players_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["-popularity_score"], name="games_popularity_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["min_age", "min_players"], name="games_age_players_idx"),
        ),
    ]
