# Generated by Django 4.2.7 on 2026-03-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0009_alter_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="name_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
