# Generated by Django 4.2.29 on 2026-03-12 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0010_game_games_min_age_idx_game_games_min_players_idx_and_more"),
        ("games", "0010_game_name_fr"),
    ]

    operations = []
