# Generated by Django 4.2.29 on 2026-03-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0012_alter_game_name_fr_no_null"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="nom_genre",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="platform",
            old_name="nom_plateforme",
            new_name="name",
        ),
    ]
