# Generated by Django 4.2.29 on 2026-04-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_rename_nom_genre_genre_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("igdb_id", models.PositiveBigIntegerField(help_text="ID vidéo côté IGDB")),
                ("name", models.CharField(blank=True, max_length=255)),
                ("video_id", models.CharField(help_text="Identifiant YouTube pour l'embed", max_length=32)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="game_videos", to="games.game")),
            ],
            options={
                "verbose_name": "Game Video",
                "verbose_name_plural": "Game Videos",
            },
        ),
        migrations.CreateModel(
            name="GameScreenshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=500)),
                ("position", models.PositiveSmallIntegerField(help_text="Ordre d'affichage (0 = première image)")),
                ("igdb_id", models.PositiveBigIntegerField(blank=True, help_text="ID IGDB pour déduplication", null=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="screenshots", to="games.game")),
            ],
            options={
                "verbose_name": "Game Screenshot",
                "verbose_name_plural": "Game Screenshots",
                "ordering": ["position", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="gamevideo",
            constraint=models.UniqueConstraint(fields=("game", "igdb_id"), name="unique_game_video_igdb_id"),
        ),
    ]
