# Generated by Django 4.2.29 on 2026-04-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_gamevideo_gamescreenshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="steam_appid",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
