# Generated by Django 4.2.30 on 2026-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0017_game_xbox_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="igdb_rating_count",
            field=models.IntegerField(default=0),
        ),
    ]
