# Generated by Django 4.2.30 on 2026-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0018_add_igdb_rating_count"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["-igdb_rating_count"], name="games_rating_count_idx"),
        ),
    ]
