# Generated by Django 4.2.7 on 2025-12-14 22:51

from django.db import migrations, models

import apps.reviews.validators


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(validators=[apps.reviews.validators.validate_review_content_length]),
        ),
    ]
