# Generated by Django 4.2.7 on 2026-01-28 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0002_alter_review_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_type", models.CharField(choices=[("review", "Review"), ("rating", "Rating")], max_length=20)),
                ("target_id", models.PositiveBigIntegerField()),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reporter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="content_reports", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Content report",
                "verbose_name_plural": "Content reports",
                "indexes": [models.Index(fields=["target_type", "target_id"], name="reviews_con_target__775344_idx")],
                "unique_together": {("reporter", "target_type", "target_id")},
            },
        ),
    ]
