# Generated by Django 4.2.7 on 2026-01-29 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0003_contentreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentreport",
            name="handled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="handled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="handled_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="handled_reports", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
