# Generated by Django 4.2.29 on 2026-04-02 12:44

from django.db import migrations, models

import apps.reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_contentreport_handled_contentreport_handled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(blank=True, default="", validators=[apps.reviews.validators.validate_review_content_length]),
        ),
    ]
