# Generated by Django 4.2.7 on 2026-01-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_add_messageread_and_drop_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="type",
            field=models.CharField(choices=[("direct", "Direct"), ("group", "Group")], default="direct", max_length=10),
        ),
    ]
