# Generated by Django 4.2.30 on 2026-05-15 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_drop_legacy_game_ticket_tables"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="supportticket",
            new_name="support_sup_status_52a4ed_idx",
            old_name="support_sup_status_2b8c8e_idx",
        ),
    ]
